# Project-wide Gradle settings.
# http://www.gradle.org/docs/current/userguide/build_environment.html

# 1. OPTIMIZACIÓN DE HARDWARE MÓVIL
# Reducimos la RAM del compilador a 1.5 GB y usamos un recolector de basura más rápido
org.gradle.jvmargs=-Xmx1536m -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Activamos el guardado inteligente para que no re-compile lo que ya está hecho
org.gradle.caching=true
org.gradle.configuration-cache=true

# Apaga el demonio de Gradle al terminar para liberar la RAM de tu teléfono inmediatamente
org.gradle.daemon=false
org.gradle.parallel=false

# 2. OPTIMIZACIÓN ESPECÍFICA PARA AGP 9.x
android.builtInKotlin=true

# 3. SOPORTE ANDROIDX Y ESTILOS
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
