package com.openplayer.music.ui.theme

import androidx.compose.ui.graphics.Color

// ----- Tema Claro -----
val LightPrimary = Color(0xFFB3261E)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFF9DEDC)
val LightOnPrimaryContainer = Color(0xFF410002)
val LightSecondary = Color(0xFF775652)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDAD5)
val LightOnSecondaryContainer = Color(0xFF2C1512)
val LightTertiary = Color(0xFF16A34A)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDCFCE7)
val LightOnTertiaryContainer = Color(0xFF052E16)
val LightError = Color(0xFFDC2626)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFEE2E2)
val LightOnErrorContainer = Color(0xFF450A0A)
val LightBackground = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF1C1B1A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1C1B1A)
val LightSurfaceVariant = Color(0xFFF2F2F2)
val LightOnSurfaceVariant = Color(0xFF525252)
val LightOutline = Color(0xFF857370)
val LightOutlineVariant = Color(0xFF1A1A1A)
val LightScrim = Color(0xFFE0E0E0)
val LightInverseOnSurface = Color(0xFF1A1A1A)
val LightFloatingIcon = Color(0xFFD9D9D9)

// Colores específicos para iconos de tema (sol/luna)
val LightSunIconColor = Color(0xFF1A1A1A)

// ----- Tema Oscuro -----
val DarkPrimary = Color(0xFFF2B8B0)
val DarkOnPrimary = Color(0xFF601410)
val DarkPrimaryContainer = Color(0xFF8C1D18)
val DarkOnPrimaryContainer = Color(0xFFF9DEDC)
val DarkSecondary = Color(0xFFE7BDB7)
val DarkOnSecondary = Color(0xFF442926)
val DarkSecondaryContainer = Color(0xFF5D3F3B)
val DarkOnSecondaryContainer = Color(0xFFFFDAD5)
val DarkTertiary = Color(0xFF4ADE80)
val DarkOnTertiary = Color(0xFF052E16)
val DarkTertiaryContainer = Color(0xFF166534)
val DarkOnTertiaryContainer = Color(0xFFDCFCE7)
val DarkError = Color(0xFFF87171)
val DarkOnError = Color(0xFF450A0A)
val DarkErrorContainer = Color(0xFF7F1D1D)
val DarkOnErrorContainer = Color(0xFFFEE2E2)
val DarkBackground = Color(0xFF151515)
val DarkOnBackground = Color(0xFFE6E1E0)
val DarkSurface = Color(0xFF151515)
val DarkOnSurface = Color(0xFFE6E1E0)
val DarkSurfaceVariant = Color(0xFF262626)
val DarkOnSurfaceVariant = Color(0xFFB3B3B3)
val DarkOutline = Color(0xFFA08C89)
val DarkOutlineVariant = Color(0xFFE5E5E5)
val DarkScrim = Color(0xFF363636)
val DarkInverseOnSurface = Color(0xFFF5F5F5)
val DarkFloatingIcon = Color(0xFF333333)

// Colores específicos para iconos de tema (sol/luna)
val DarkMoonIconColor = Color(0xFFF5F5F5)

// ----- Tema AMOLED (negro puro) -----
val AmoledPrimary = Color(0xFFF2B8B0)
val AmoledOnPrimary = Color(0xFF601410)
val AmoledPrimaryContainer = Color(0xFF8C1D18)
val AmoledOnPrimaryContainer = Color(0xFFF9DEDC)
val AmoledSecondary = Color(0xFFE7BDB7)
val AmoledOnSecondary = Color(0xFF442926)
val AmoledSecondaryContainer = Color(0xFF3A2522)
val AmoledOnSecondaryContainer = Color(0xFFFFDAD5)
val AmoledTertiary = Color(0xFF22C55E)
val AmoledOnTertiary = Color(0xFF052E16)
val AmoledTertiaryContainer = Color(0xFF14532D)
val AmoledOnTertiaryContainer = Color(0xFFDCFCE7)
val AmoledError = Color(0xFFEF4444)
val AmoledOnError = Color(0xFF450A0A)
val AmoledErrorContainer = Color(0xFF7F1D1D)
val AmoledOnErrorContainer = Color(0xFFFEE2E2)
val AmoledBackground = Color(0xFF000000)
val AmoledOnBackground = Color(0xFFE6E1E0)
val AmoledSurface = Color(0xFF000000)
val AmoledOnSurface = Color(0xFFE6E1E0)
val AmoledSurfaceVariant = Color(0xFF151515)
val AmoledOnSurfaceVariant = Color(0xFFA3A3A3)
val AmoledOutline = Color(0xFF8A7673)
val AmoledOutlineVariant = Color(0xFFD4D4D4)
val AmoledScrim = Color(0xFF222222)
val AmoledInverseOnSurface = Color(0xFFE5E5E5)
val AmoledFloatingIcon = Color(0xFF212121)

// Colores específicos para iconos de tema (sol/luna)
val AmoledMoonIconColor = Color(0xFFE5E5E5)